#!/bin/bash
echo -e '\033[1m 1.map\033[0m'
./lem-in 1.map

echo -e '\033[1m 2.map\033[0m'
./lem-in 2.map

echo -e '\033[1m 3.map\033[0m'
./lem-in 2.map

echo -e '\033[1m maps/valid/vs/one_way/1.map \033[0m'
./lem-in maps/valid/vs/one_way/1.map
echo -e '\033[1m maps/valid/vs/one_way/2.map \033[0m'
./lem-in maps/valid/vs/one_way/2.map
echo -e '\033[1m maps/valid/vs/one_way/3.map \033[0m'
./lem-in maps/valid/vs/one_way/3.map
echo -e '\033[1m maps/valid/vs/one_way/4.map \033[0m'
./lem-in maps/valid/vs/one_way/4.map
echo -e '\033[1m maps/valid/vs/one_way/5.map \033[0m'
./lem-in maps/valid/vs/one_way/5.map

echo -e '\033[1m  maps/valid/vs/multiple_ways/1.map \033[0m'
 ./lem-in maps/valid/vs/multiple_ways/1.map
echo -e '\033[1m  maps/valid/vs/multiple_ways/2.map \033[0m'
  ./lem-in maps/valid/vs/multiple_ways/2.map
echo -e '\033[1m  maps/valid/vs/multiple_ways/3.map \033[0m'
   ./lem-in maps/valid/vs/multiple_ways/3.map
echo -e '\033[1m  maps/valid/vs/multiple_ways/4.map \033[0m'
    ./lem-in maps/valid/vs/multiple_ways/4.map
echo -e '\033[1m  maps/valid/vs/multiple_ways/5.map \033[0m'
     ./lem-in maps/valid/vs/multiple_ways/5.map
echo -e '\033[1m  maps/valid/vs/multiple_ways/6.map \033[0m'
      ./lem-in maps/valid/vs/multiple_ways/6.map
echo -e '\033[1m  maps/valid/vs/multiple_ways/7.map \033[0m'
       ./lem-in maps/valid/vs/multiple_ways/7.map
echo -e '\033[1m  maps/valid/vs/multiple_ways/8.map \033[0m'
        ./lem-in maps/valid/vs/multiple_ways/8.map


echo -e '\033[1m  maps/valid/difficult/one_name_with_dashes.map \033[0m'
./lem-in maps/valid/difficult/one_name_with_dashes.map

echo -e '\033[1m  maps/valid/difficult/two_names_with_dashes.map  \033[0m'
./lem-in maps/valid/difficult/two_names_with_dashes.map

echo -e '\033[1m  maps/valid/difficult/three_ways.map \033[0m'
./lem-in maps/valid/difficult/three_ways.map
