#!/bin/bash
make

echo -e '\033[1m  maps/valid/difficult/three_ways.map \033[0m'
./lem-in maps/valid/difficult/three_ways.map -p

echo -e '\033[1m  mapbig  \033[0m'
./lem-in maps/mapbig -p

echo -e '\033[1m  mapch  \033[0m'
./lem-in maps/mapch -p
